# SPDX-License-Identifier: GPL-2.0

powervrsgx-y := \
	bridged_pvr_bridge.o \
	bridged_sgx_bridge.o \
	bridged_support.o \
	buffer_manager.o \
	deviceclass.o \
	devicemem.o \
	event.o \
	handle.o \
	hash.o \
	lists.o \
	mem.o \
	metrics.o \
	mm.o \
	mmap.o \
	module.o \
	mutex.o \
	omap3_sysconfig.o \
	omap3_sysutils.o \
	osfunc.o \
	osperproc.o \
	pdump.o \
	perproc.o \
	power.o \
	proc.o \
	pvr_bridge_k.o \
	pvr_debug.o \
	pvrsrv.o \
	queue.o \
	ra.o \
	resman.o \
	sgxinit.o \
	sgxkick.o \
	sgxmmu.o \
	sgxpb.o \
	sgxpower.o \
	sgxreset.o \
	sgxtransfer.o \
	sgxutils.o

obj-$(CONFIG_DRM_POWERVRSGX) += powervrsgx.o
